services:
  # nginx:
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   image: nginx
  #   volumes:
  #     - ./requirements/nginx/config:/etc/nginx/conf.d
  #   ports:
  #     - "5050:5050"
  #   restart: always
    
  mariadb:
    # image: mariadb:latest
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: "my_data"
      MYSQL_USER: "svevish"
      MYSQL_PASSWORD: "3"
    container_name: db
    networks:
      - my_network
    ports:
      - 3306:3306
    # volumes:
    #   - ./requirements/mariadb/tools:/var/lib/mysql
    restart: always
  # wordpress:
  #   image: wordpress
  #   container_name: wp
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: sve
  #     WORDPRESS_DB_PASSWORD: password1
  #     WORDPRESS_DB_NAME: my_database
  #   networks:
  #     my_custom_network:
  #       ipv4_address: 172.19.0.3
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./requirements/wordpress/config/wp-config.php:/var/www/html/wp-config.php
  #   restart: always
  
networks:
  my_network:
    external: true
    name: net