services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    volumes:
      - ./requirements/nginx/config:/etc/nginx/conf.d
    ports:
      - "5050:5050"
    restart: always
    
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: some-maria
    networks:
      - my_network
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./requirements/mariadb/config:/docker-entrypoint-initdb.d
  wordpress:
    depends_on:
      mariadb:
        condition: service_started
        required: true
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: some-maria:3306
      WORDPRESS_DB_USER: sve
      WORDPRESS_DB_PASSWORD: password1
      WORDPRESS_DB_NAME: my_database
    networks:
      - my_network
    ports:
      - "8080:80"
    restart: always
  
networks:
  my_network:
    name: test
