services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: ng
    volumes:
      - wp_files:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - my_network
    restart: always
    depends_on:
      - wordpress
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - db_password
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER_DB}
      - MYSQL_PASSWORD=/run/secrets/db_password
    container_name: db
    networks:
      - my_network
    ports:
      - 3306:3306
    volumes:
      - wordpress_db:/var/lib/mysql
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wp
    secrets:
      - db_password
      - admin_password
    environment:
      - WORDPRESS_DB_NAME=${DATABASE}
      - WORDPRESS_DB_USER=${USER_DB}
      - WORDPRESS_DB_PASSWORD=/run/secrets/db_password
      - WORDPRESS_DB_HOST=${HOST}
      - DOMAIN=${DOMAIN}
      - PORT=${PORT}
      - TITLE=${TITLE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=/run/secrets/admin_password
    networks:
      - my_network
    ports:
      - 9000:9000
    volumes:
      - wp_files:/var/www/html/
    depends_on:
      - mariadb
    restart: always

volumes:
  wp_files:
  wordpress_db:
networks:
  my_network:
secrets:
  db_password:
    file: ./secrets/db_password.txt
  admin_password:
    file: ./secrets/admin_password.txt